version: "3.7"

services:
  blog:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`kiana.moe`)"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadBalancer.server.port=80"
    networks:
      - traefiknet

networks:
  traefiknet:
    external:
      name: traefiknet